version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: messaging_db
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: messaging_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_NAME: messaging_db
      DB_USER: messaging_user
      DB_PASSWORD: messaging_pass
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
