apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app-blue
  labels:
    app: django-messaging-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: django-messaging-app
        version: blue
    spec:
      containers:
      - name: django-app
        image: django-messaging-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "True"
        - name: DJANGO_SETTINGS_MODULE
          value: "messaging_app.settings"
        - name: VERSION
          value: "blue"
